# 基本张量运算

使用TensorFlow v2的基本张量操作

In [1]:
from __future__ import print_function
import tensorflow as tf

In [2]:
# 定义张量常量
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

In [3]:
# 各种张量运算
# 张量也支持python操作符(+，*，…)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

# 获取张量计算值
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [4]:
# 更多运算
# tf.reduce_mean 函数用于计算张量tensor沿着指定的数轴（tensor的某一维度）上的的平均值
# 第一个参数input_tensor：输入的待降维的tensor;
# 第二个参数axis：指定的轴，如果不指定，则计算所有元素的均值;
# 第三个参数keep_dims：是否降维度，设置为True，输出的结果保持输入tensor的形状，设置为False，输出结果会降低维度;
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [5]:
# 矩阵乘法
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

product = tf.matmul(matrix1, matrix2)

In [6]:
# 显示张量
product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [7]:
# Convert Tensor to Numpy.
product.numpy()

array([[19, 22],
       [43, 50]], dtype=int32)